### ISSUE TITLE
[BUG] Docker-compose/volume : no declaration was found in the volumes section

### ISSUE THREAD

**Issue by developerasun** [developerasun/myCodeBox-devOps#3]
## issue - describe what happened
body : named volume in docker-compose.yml not working when they are declared

```yml
version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
directory in container
    volumes:
      - test:/data
  redis:
    image: "redis:alpine" 
```

## circumstances - add screenshot here
screenshot :
![named-volume-not-found](https://user-images.githubusercontent.com/83855174/158842026-842764e1-5f62-43c0-b358-9cb301f23b74.png)
